apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
{{- include "example-app.mongoLabels" . | nindent 4 }}
spec:
  replicas:  {{ .Values.deployment.mongo.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
{{- include "example-app.mongoLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          resources:
            {{- toYaml .Values.deployment.mongo.resources | nindent 11 }}
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "pvc"




